name: cantwait28
description: A Flutter project that counts days down to exciting dates in the future.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.5

  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  firebase_ui_auth: ^1.11.1
  intl: ^0.18.1
  firebase_auth: ^4.17.5
  bloc: ^8.1.0
  

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
